services:
  apigateway:
    build:
      context: .
      dockerfile: src/API/APIGateway/Dockerfile
    container_name: APIGateway
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      JWT__Key: ${JWT_KEY}
      Authentication__Client__Scopes: api.read,api.write
      Authentication__Client__Audiences: finances-api,user-api
      Authentication__Authority: http://usersapi:8080/
    depends_on:
      - financesapi
      - usersapi
      - db

  financesapi:
    build:
      context: .
      dockerfile: src/API/RightTest.FinancesAPI/Dockerfile
    container_name: FinancesAPI
    ports:
      - "5010:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: ${ConnectionStrings__FinancesConnection}
      JWT__Key: ${JWT_KEY}
      Authentication__Issuer: http://usersapi:8080/
      Authentication__Client__Scopes: api.read,api.write
    depends_on:
      - db

  usersapi:
    build:
      context: .
      dockerfile: src/API/RightTest.UsersAPI/Dockerfile
    container_name: UsersAPI
    ports:
      - "5020:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: ${ConnectionStrings__UsersConnection}
      JWT__Key: ${JWT_KEY}
      JWT__Scopes: api.read,api.write
      JWT__Issuer: http://usersapi:8080/
      JWT__Audiences: finances-api
      JWT__ValidHours: 24
    depends_on:
      - db

  migrationapi:
    build:
      context: .
      dockerfile: src/API/RightTest.MigrationsAPI/Dockerfile
    container_name: MigrationsAPI
    ports:
      - "5030:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__FinancesConnection: ${ConnectionStrings__FinancesConnection}
      ConnectionStrings__UsersConnection: ${ConnectionStrings__UsersConnection}
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: Finances
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB__PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: