services:
  apigateway:
    build:
      context: .
      dockerfile: src/API/APIGateway/Dockerfile
    container_name: APIGateway
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      JWT__Key: Ibhja8vSTKQkydr0pImpjnCqx++8mwtAmYGpBvxxKvNn6m53nizbvgt52jEzBcJeXrhaGYovIPtAKj+3ecmQkA==
    depends_on:
      - financesapi
      - usersapi
      - db

  financesapi:
    build:
      context: .
      dockerfile: src/API/RightTest.FinancesAPI/Dockerfile
    container_name: FinancesAPI
    ports:
      - "5010:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=Finances;Username=postgres;Password=124124
    depends_on:
      - db

  usersapi:
    build:
      context: .
      dockerfile: src/API/RightTest.UsersAPI/Dockerfile
    container_name: UsersAPI
    ports:
      - "5020:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=Users;Username=postgres;Password=124124
      JWT__Key: Ibhja8vSTKQkydr0pImpjnCqx++8mwtAmYGpBvxxKvNn6m53nizbvgt52jEzBcJeXrhaGYovIPtAKj+3ecmQkA==
      JWT__ValidHours: 24
    depends_on:
      - db

  migrationapi:
    build:
      context: .
      dockerfile: src/API/RightTest.MigrationsAPI/Dockerfile
    container_name: MigrationsAPI
    ports:
      - "5030:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__FinancesConnection: Host=db;Port=5432;Database=Finances;Username=postgres;Password=124124
      ConnectionStrings__UsersConnection: Host=db;Port=5432;Database=Users;Username=postgres;Password=124124
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: Finances
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 124124
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: